import type { AIHarnessToolDefinition } from "@/lib/ai/harness/types";

export const AI_HARNESS_TOOLS = [
  {
    category: "sales",
    description: "Sugere resposta comercial para a conversa atual.",
    label: "Sugerir resposta",
    requiresLLM: true,
    tool: "sales.suggest_reply",
  },
  {
    category: "sales",
    description: "Detecta objeções do lead nas mensagens recentes.",
    label: "Detectar objeção",
    requiresLLM: true,
    tool: "sales.detect_objection",
  },
  {
    category: "sales",
    description: "Gera resposta ética para quebrar uma objeção.",
    label: "Quebrar objeção",
    requiresLLM: true,
    tool: "sales.break_objection",
  },
  {
    category: "sales",
    description: "Classifica temperatura do lead.",
    label: "Temperatura do lead",
    requiresLLM: true,
    tool: "sales.classify_lead_temperature",
  },
  {
    category: "sales",
    description: "Resume a sessão de venda.",
    label: "Resumir conversa",
    requiresLLM: true,
    tool: "sales.summarize_session",
  },
  {
    category: "sales",
    description: "Rascunha mensagem de checkout para aprovação humana.",
    label: "Mensagem de checkout",
    requiresLLM: true,
    tool: "sales.generate_checkout_message",
  },
  {
    category: "sales",
    description: "Sugere a próxima melhor ação comercial.",
    label: "Próxima ação",
    requiresLLM: true,
    tool: "sales.suggest_next_action",
  },
  {
    category: "sales",
    description: "Explica benefícios reais do produto.",
    label: "Benefícios",
    requiresLLM: true,
    tool: "sales.explain_product_benefits",
  },
  {
    category: "sales",
    description: "Compara necessidade do cliente com o produto.",
    label: "Comparar necessidade",
    requiresLLM: true,
    tool: "sales.compare_need_with_product",
  },
  {
    category: "sales",
    description: "Gera nota para transferência comercial.",
    label: "Nota de transferência",
    requiresLLM: true,
    tool: "sales.generate_transfer_note",
  },
  {
    category: "sales",
    description: "Gera mensagem de follow-up.",
    label: "Follow-up",
    requiresLLM: true,
    tool: "sales.generate_followup_message",
  },

  {
    category: "support",
    description: "Sugere resposta para suporte.",
    label: "Sugerir resposta",
    requiresLLM: true,
    tool: "support.suggest_reply",
  },
  {
    category: "support",
    description: "Identifica motivo do suporte.",
    label: "Identificar motivo",
    requiresLLM: true,
    tool: "support.identify_reason",
  },
  {
    category: "support",
    description: "Sugere resolução com base no contexto.",
    label: "Sugerir resolução",
    requiresLLM: true,
    tool: "support.suggest_resolution",
  },
  {
    category: "support",
    description: "Resume a sessão de suporte.",
    label: "Resumir suporte",
    requiresLLM: true,
    tool: "support.summarize_session",
  },
  {
    category: "support",
    description: "Gera nota de continuidade.",
    label: "Nota de continuidade",
    requiresLLM: true,
    tool: "support.generate_continuity_note",
  },
  {
    category: "support",
    description: "Gera nota de escalação interna.",
    label: "Escalação interna",
    requiresLLM: true,
    tool: "support.generate_escalation_note",
  },
  {
    category: "support",
    description: "Detecta frustração do cliente.",
    label: "Detectar frustração",
    requiresLLM: true,
    tool: "support.detect_frustration",
  },
  {
    category: "support",
    description: "Sugere handoff humano.",
    label: "Handoff humano",
    requiresLLM: true,
    tool: "support.suggest_handoff",
  },
  {
    category: "support",
    description: "Explica próximos passos de suporte.",
    label: "Passos de suporte",
    requiresLLM: true,
    tool: "support.explain_steps",
  },
  {
    category: "support",
    description: "Gera mensagem de fechamento para aprovação humana.",
    label: "Fechamento",
    requiresLLM: true,
    tool: "support.generate_closing_message",
  },

  {
    category: "chat",
    description: "Reescreve a mensagem selecionada.",
    label: "Reescrever",
    requiresLLM: true,
    tool: "chat.rewrite_message",
  },
  {
    category: "chat",
    description: "Encurta a mensagem.",
    label: "Encurtar",
    requiresLLM: true,
    tool: "chat.shorten_message",
  },
  {
    category: "chat",
    description: "Humaniza a mensagem.",
    label: "Humanizar",
    requiresLLM: true,
    tool: "chat.make_more_human",
  },
  {
    category: "chat",
    description: "Torna a mensagem mais profissional.",
    label: "Profissionalizar",
    requiresLLM: true,
    tool: "chat.make_more_professional",
  },
  {
    category: "chat",
    description: "Torna a mensagem mais persuasiva.",
    label: "Persuasiva",
    requiresLLM: true,
    tool: "chat.make_more_persuasive",
  },
  {
    category: "chat",
    description: "Extrai dados do cliente.",
    label: "Extrair dados",
    requiresLLM: true,
    tool: "chat.extract_customer_data",
  },
  {
    category: "chat",
    description: "Detecta intenção do cliente.",
    label: "Detectar intenção",
    requiresLLM: true,
    tool: "chat.detect_intent",
  },
  {
    category: "chat",
    description: "Detecta risco na conversa.",
    label: "Detectar risco",
    requiresLLM: true,
    tool: "chat.detect_risk",
  },
  {
    category: "chat",
    description: "Resume mensagens recentes.",
    label: "Resumo recente",
    requiresLLM: true,
    tool: "chat.summarize_recent_messages",
  },

  {
    category: "product",
    description: "Retorna contexto do produto.",
    label: "Contexto do produto",
    requiresLLM: false,
    tool: "product.get_context",
  },
  {
    category: "product",
    description: "Lista benefícios do produto.",
    label: "Benefícios do produto",
    requiresLLM: true,
    tool: "product.get_benefits",
  },
  {
    category: "product",
    description: "Explica preço do produto.",
    label: "Preço",
    requiresLLM: true,
    tool: "product.get_price_info",
  },
  {
    category: "product",
    description: "Resume estoque do produto.",
    label: "Estoque",
    requiresLLM: false,
    tool: "product.get_stock_status",
  },
  {
    category: "product",
    description: "Resume checkout do produto.",
    label: "Checkout",
    requiresLLM: false,
    tool: "product.get_checkout_info",
  },
  {
    category: "product",
    description: "Busca na base de conhecimento.",
    label: "Buscar conhecimento",
    requiresLLM: true,
    tool: "product.search_knowledge_base",
  },
  {
    category: "product",
    description: "Gera resposta pública sobre o produto.",
    label: "Resposta pública",
    requiresLLM: true,
    tool: "product.generate_public_answer",
  },

  {
    category: "ops",
    description: "Gera nota interna operacional.",
    label: "Nota interna",
    requiresLLM: true,
    tool: "ops.generate_internal_note",
  },
  {
    category: "ops",
    description: "Resume eventos para auditoria.",
    label: "Resumo de auditoria",
    requiresLLM: true,
    tool: "ops.generate_audit_summary",
  },
  {
    category: "ops",
    description: "Sugere prioridade do ticket.",
    label: "Prioridade",
    requiresLLM: true,
    tool: "ops.suggest_ticket_priority",
  },
  {
    category: "ops",
    description: "Detecta possível ticket duplicado.",
    label: "Duplicidade",
    requiresLLM: true,
    tool: "ops.detect_duplicate_ticket",
  },
  {
    category: "ops",
    description: "Prepara contexto para transferência.",
    label: "Contexto de transferência",
    requiresLLM: true,
    tool: "ops.prepare_transfer_context",
  },
  {
    category: "ops",
    description: "Prepara handoff humano.",
    label: "Handoff",
    requiresLLM: true,
    tool: "ops.prepare_human_handoff",
  },

  {
    category: "ai",
    description: "Testa o modelo global configurado.",
    label: "Testar modelo",
    requiresLLM: true,
    tool: "ai.test_global_model",
  },
  {
    category: "ai",
    description: "Estima uso da chamada atual.",
    label: "Estimar uso",
    requiresLLM: false,
    tool: "ai.estimate_usage",
  },
  {
    category: "ai",
    description: "Verifica limites do agente.",
    label: "Checar limites",
    requiresLLM: false,
    tool: "ai.check_agent_limits",
  },
  {
    category: "ai",
    description: "Registra resposta ruim.",
    label: "Marcar resposta ruim",
    requiresLLM: false,
    tool: "ai.register_bad_response",
  },
  {
    category: "ai",
    description: "Gera prévia do prompt.",
    label: "Prévia do prompt",
    requiresLLM: false,
    tool: "ai.generate_prompt_preview",
  },
] as const satisfies readonly AIHarnessToolDefinition[];

export type AIHarnessTool = (typeof AI_HARNESS_TOOLS)[number]["tool"];

export function getAIHarnessTool(tool: string) {
  return AI_HARNESS_TOOLS.find((item) => item.tool === tool);
}

export function getAIHarnessToolsByCategory(
  category: AIHarnessToolDefinition["category"],
) {
  return AI_HARNESS_TOOLS.filter((item) => item.category === category);
}
